#!/bin/sh

SCRIPT="stanchion-admin"

PLATFORM_BASE_DIR={{platform_base_dir}}
PLATFORM_BASE_DIR=${PLATFORM_BASE_DIR:-$(cd $(dirname "$0")/.. && pwd -P)}

PLATFORM_BIN_DIR={{platform_bin_dir}}
if [ "$PLATFORM_BIN_DIR" = "${PLATFORM_BIN_DIR#/}" ]; then
    PLATFORM_BIN_DIR=$PLATFORM_BASE_DIR/$PLATFORM_BIN_DIR
fi

PLATFORM_LIB_DIR={{platform_lib_dir}}
if [ "$PLATFORM_LIB_DIR" = "${PLATFORM_LIB_DIR#/}" ]; then
    PLATFORM_LIB_DIR=$PLATFORM_BASE_DIR/$PLATFORM_LIB_DIR
fi
. $PLATFORM_LIB_DIR/lib.sh

usage() {
    echo "Usage: $SCRIPT { version | status }"
}

case "$1" in
    version)
        shift
        rpc stanchion_console version
        ;;
    status)
        shift
        rpc stanchion_console status
        ;;
    *)
        usage
        exit 1
        ;;
esac

# No explicit exit from within script or nodetool, assumed to have succeeded.
exit 0
