#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

SCRIPT=$(readlink $0 || true)
if [ -z $SCRIPT ]; then
    SCRIPT=$0
fi

SCRIPT_DIR="$(cd `dirname "$SCRIPT"` && pwd -P)"

RPC_HOP=$SCRIPT_DIR/stanchion

usage() {
    echo "Usage: $SCRIPT { status }"
}

# Check the first argument for instructions
case "$1" in
    status)
        shift
        $RPC_HOP rpc stanchion_console status
        ;;
    *)
        usage
        exit 1
        ;;
esac
